Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2024-07, with the labels that each got.

#214 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#216 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_asm.go
  vendor/github.com/cespare/xxhash/v2/xxhash_other.go
  vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand_go1.21.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#217 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, approved, lgtm

#215 Added the target revisions scaling down into the Spec.StageTargetRevisions
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: size/M, approved, lgtm

#219 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#222 Changed the branch of serving back to main in github action
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#224 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#226 Unify config key for stage rollout timeout option
  pkg/reconciler/service/config.go
  pkg/reconciler/service/config_test.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
Labels: size/M, approved, ok-to-test, lgtm, kind/cleanup
