Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2024-02, with the labels that each got.

#64 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#65 Enabled the support of the transition from multiple revisions to one revision
  pkg/apis/serving/v1/rolloutorchestrator_lifecycle.go
  pkg/reconciler/common/deployment.go
  pkg/reconciler/rolloutorchestrator/controller.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: size/XL, approved, lgtm

#69 Removed the controller for the certificate
  cmd/controller/main.go
  go.mod
  go.sum
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  vendor/knative.dev/networking/pkg/certificates/certs.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/key_pair.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/certificates.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/controller.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/controller_impl.go
  vendor/knative.dev/networking/pkg/certificates/reconciler/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/filtered/secret.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/reconciler/revision/cruds.go
  vendor/knative.dev/serving/pkg/reconciler/revision/reconcile_resources.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/pa.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#68 Remove the unnecessary deploy check during the scaling up
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
Labels: approved, size/XS, lgtm

#72 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/reconciler/nscert/nscert.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#73 Fix the issue when recreating the RO
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/service.go
Labels: size/M, approved, lgtm

#71 Enable the annotation key to configure the progressive rollout
  pkg/reconciler/service/config.go
  pkg/reconciler/service/config_test.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
Labels: approved, size/S, lgtm

#76 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#77 Updated the RO, when the spec is changed
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/resources/rolloutorchestrator_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: size/M, approved, lgtm

#79 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#80 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#82 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#81 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/pkg/homedir/homedir.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_linux.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_others.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_windows.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#87 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/factory.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#89 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#90 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/LICENSE
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
