Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2024-08, with the labels that each got.

#227 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#229 Updated based on linting
  cmd/autoscaler/leaderelection.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/testing/v1/factory.go
Labels: size/XL, approved, lgtm

#230 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/S, lgtm
