Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2024-05, with the labels that each got.

#166 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#165 Clean up the SPA when revision is deleted
  pkg/reconciler/rolloutorchestrator/controller.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator_test.go
Labels: size/M, approved, lgtm

#171 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#167 Implementation of the resourceUtil mode for the progressive rollout
  config/core/300-resources/rolloutorchestrator.yaml
  config/core/configmaps/config-rolloutorchestrator.yaml
  pkg/apis/serving/v1/rolloutorchestrator_types.go
  pkg/reconciler/rolloutorchestrator/controller.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator_test.go
  pkg/reconciler/rolloutorchestrator/strategies/base.go
  pkg/reconciler/rolloutorchestrator/strategies/base_test.go
  pkg/reconciler/rolloutorchestrator/strategies/strategy.go
  pkg/reconciler/service/config.go
  pkg/reconciler/service/config_test.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/service.go
Labels: approved, size/XXL, lgtm

#172 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#176 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, skip-review

#180 [release-1.13] Make the branch configurable for Serving
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#178 Configure the branch of Knative Serving repository
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#179 [release-1.14] Make the branch configurable for Serving
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#175 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/resources/services.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#177 Reset the SPAs for revisions that are obsolete
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/service.go
Labels: size/M, approved, lgtm

#186 Refactored the functions cleanUpSPAs and resetObsoleteSPAs
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
Labels: size/M, approved, lgtm

#189 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/google.golang.org/grpc/CONTRIBUTING.md
  vendor/google.golang.org/grpc/MAINTAINERS.md
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codegen.sh
  vendor/google.golang.org/grpc/codes/codes.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/config.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/gracefulswitch.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcutil/compressor.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/peer/peer.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/stream_interfaces.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#194 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/reconciler/route/route.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#192 Updated the status before returning nil in reconcile
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/rolloutorchestrator/strategies/base.go
  pkg/reconciler/rolloutorchestrator/strategies/strategy.go
Labels: size/M, approved, lgtm

#197 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#198 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#199 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/resources/services.go
  vendor/modules.txt
Labels: approved, size/S, lgtm
