Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2024-12, with the labels that each got.

#257 Updated the dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, approved, lgtm

#259 Updated the chainguard-dev/actions/setup-kind version
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#260 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, size/S, lgtm

#261 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#262 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm
