Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2024-01, with the labels that each got.

#51 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#52 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#54 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#55 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#57 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#37 Add the implementation of the service controller
  .github/workflows/kind-e2e.yaml
  cmd/controller/main.go
  config/core/300-resources/rolloutorchestrator.yaml
  config/core/configmaps/config-rolloutorchestrator.yaml
  go.mod
  pkg/apis/serving/v1/rolloutorchestrator_lifecycle.go
  pkg/apis/serving/v1/rolloutorchestrator_lifecycle_test.go
  pkg/apis/serving/v1/rolloutorchestrator_types.go
  pkg/apis/serving/v1/zz_generated.deepcopy.go
  pkg/reconciler/common/constvars.go
  pkg/reconciler/rolloutorchestrator/controller.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator_test.go
  pkg/reconciler/service/config.go
  pkg/reconciler/service/config_test.go
  pkg/reconciler/service/controller.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/resources/rolloutorchestrator_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#56 Updated the README and other documents for this repository
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/L

#62 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/S, lgtm

#58 Update the shift mechanism to keep the stage is within the ratio
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/service/controller.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/resources/rolloutorchestrator_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, lgtm, size/L

#63 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/context.go
  vendor/github.com/go-logr/logr/context_noslog.go
  vendor/github.com/go-logr/logr/context_slog.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr.go
  vendor/github.com/go-logr/logr/slogsink.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/version7.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_others.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_windows.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/reconciler/accessor/networking/certificate.go
  vendor/knative.dev/serving/pkg/reconciler/revision/controller.go
  vendor/knative.dev/serving/pkg/reconciler/revision/cruds.go
  vendor/knative.dev/serving/pkg/reconciler/revision/reconcile_resources.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/certificate.go
  vendor/knative.dev/serving/pkg/reconciler/revision/revision.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/certificate.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/ingress.go
  vendor/knative.dev/serving/pkg/reconciler/route/route.go
  vendor/knative.dev/serving/pkg/reconciler/service/service.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
