Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2024-04, with the labels that each got.

#142 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/deploy.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/queue.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#143 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#128 Changed the TargetFinishTime into pointer and verify the deployments
  pkg/reconciler/common/deployment.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/service/controller.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/resources/rolloutorchestrator_test.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, lgtm, size/L

#150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#149 Use LastStageReady to check whether we still need to calculate next stage
  pkg/apis/serving/v1/rolloutorchestrator_lifecycle.go
  pkg/reconciler/service/service.go
Labels: approved, size/S, lgtm

#152 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#156 [release-1.13] Reset the Spec.InitialRevisions for RolloutOrchestrator the when route traffic is empty
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/resources/rolloutorchestrator_test.go
Labels: size/XL, approved, lgtm

#154 Reset the Spec.InitialRevisions for RolloutOrchestrator the when route traffic is empty
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/resources/rolloutorchestrator_test.go
Labels: size/XL, approved, lgtm

#157 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#158 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#159 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/reconciler/route/route.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#161 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#164 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
