Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2024-03, with the labels that each got.

#91 In the final stage, scaling-up finishes first
  pkg/apis/serving/v1/rolloutorchestrator_lifecycle.go
  pkg/reconciler/service/service.go
Labels: size/M, approved, lgtm

#94 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#103 Revert "In the final stage, scaling-up finishes first (#91)"
  pkg/apis/serving/v1/rolloutorchestrator_lifecycle.go
  pkg/reconciler/service/service.go
Labels: size/M, approved, lgtm

#105 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#107 In the final stage, scaling-up finishes first
  .github/workflows/kind-e2e.yaml
  pkg/apis/serving/v1/rolloutorchestrator_lifecycle.go
  pkg/apis/serving/v1/rolloutorchestrator_types.go
  pkg/reconciler/common/constvars.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/service/service.go
Labels: size/M, approved, lgtm

#112 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/knative.dev/serving/pkg/http/request_log.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#116 Added the service conversion and RolloutDuration check
  pkg/reconciler/service/config.go
  pkg/reconciler/service/config_test.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: size/M, approved, lgtm

#118 Verify the number of pods stuck on terminating
  cmd/autoscaler/main.go
  cmd/controller/main.go
  config/core/300-resources/stagepodautoscaler.yaml
  pkg/apis/serving/v1/stagepodautoscaler_types.go
  pkg/apis/serving/v1/zz_generated.deepcopy.go
  pkg/reconciler/rolloutorchestrator/controller.go
  pkg/reconciler/rolloutorchestrator/rolloutorchestrator.go
  pkg/reconciler/stagepodautoscaler/controller.go
  pkg/reconciler/stagepodautoscaler/stagepodautoscaler.go
Labels: size/M, approved, lgtm

#121 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#127 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#125 Updated the instructions on how to install and configure
  DEVELOPMENT.md
  README.md
Labels: size/M, approved, lgtm

#124 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#131 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#133 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#129 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#137 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, skip-review

#138 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/reconciler/revision/reconcile_resources.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#140 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L
