Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2025-07, with the labels that each got.

#378 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#379 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/observability/config.go
  vendor/knative.dev/pkg/observability/metrics/config.go
  vendor/knative.dev/pkg/observability/runtime/config.go
  vendor/knative.dev/pkg/observability/tracing/config.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/serving/pkg/observability/config.go
  vendor/knative.dev/serving/pkg/observability/configmap/configmap.go
  vendor/knative.dev/serving/pkg/observability/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/revision/config/store.go
  vendor/knative.dev/serving/pkg/reconciler/revision/controller.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/queue.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#382 Sync-up the kpa package for OTEL support in serving
  cmd/autoscaler/main.go
  go.mod
  go.sum
  pkg/reconciler/autoscaling/kpa/controller.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/kpa_test.go
  pkg/reconciler/autoscaling/kpa/metrics.go
  vendor/go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest/README.md
  vendor/go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest/assertion.go
  vendor/go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest/comparisons.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/knative.dev/pkg/observability/metrics/metricstest/assert.go
  vendor/knative.dev/pkg/observability/metrics/metricstest/doc.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/serving/pkg/autoscaler/metrics/collector.go
  vendor/knative.dev/serving/pkg/autoscaler/metrics/stats_scraper.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/autoscaler.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/metrics.go
  vendor/knative.dev/serving/pkg/metrics/key.go
  vendor/knative.dev/serving/pkg/metrics/newkey.go
  vendor/knative.dev/serving/pkg/metrics/tags.go
  vendor/knative.dev/serving/pkg/observability/otel/otel.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#384 Updated the dependencies for release-1.19
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm
