Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2025-04, with the labels that each got.

#306 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#303 Shift traffic when the minimum number of replicas are ready during progressive rollout
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, lgtm, size/L

#312 [release-1.16] Upgrade to golangci.yaml v2
  .golangci.yaml
Labels: size/M, approved, lgtm

#319 Ignore the case when checking the rollout strategy
  pkg/reconciler/service/service.go
Labels: approved, size/S, lgtm

#323 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/queue.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#325 Leave the resourceUtil mode as it bahaves now
  pkg/reconciler/service/service.go
Labels: size/M, approved, lgtm

#324 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#328 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/http/proxy.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#332 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/endpointsharding/endpointsharding.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/transport/client_stream.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/server_stream.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#333 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/reconciler/route/route.go
  vendor/modules.txt
Labels: approved, size/S, lgtm
