Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2025-05, with the labels that each got.

#334 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#336 Assigned 0% traffic to the new revision before reaching the minimum replicas
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, lgtm, size/L

#346 Add the condition when spa.Status.ActualScale is nil
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, lgtm, size/L

#349 [release-1.16] Add the condition when spa.Status.ActualScale is nil
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: size/M, approved, lgtm

#356 [release-1.16] Assign 0% when there is at least one pod running
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: size/M, approved, lgtm

#358 [release-1.17] Assign 0% when there is at least one pod running
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: size/M, approved, lgtm

#360 [release-1.16] Removed traffic reading from the route
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: size/M, approved, lgtm

#361 Avoid the cases when RolloutDuration is set for traffic shift
  pkg/reconciler/service/service.go
  pkg/reconciler/service/service_test.go
Labels: approved, size/S, lgtm

#363 Removed the oldest citizens which are no longer useful
  example-addressable-service.yaml
  example-simple-deployment.yaml
Labels: approved, size/S, lgtm

#364 Assigned 0% to the new revision even before any pod is ready
  pkg/reconciler/service/service.go
Labels: approved, size/XS, lgtm

#366 [release-1.17] Assigned 0% to the new revision even before any pod is ready
  pkg/reconciler/service/service.go
Labels: approved, size/XS, lgtm

#367 [release-1.16] Assigned 0% to the new revision even before any pod is ready
  pkg/reconciler/service/service.go
Labels: approved, size/XS, lgtm

#369 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#371 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: size/M, approved, lgtm
