Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2025-01, with the labels that each got.

#263 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#264 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#265 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#267 Fixed the lint issues
  .golangci.yaml
  pkg/reconciler/rolloutorchestrator/strategies/base.go
  pkg/reconciler/service/resources/rolloutorchestrator.go
  pkg/reconciler/service/resources/rolloutorchestrator_test.go
Labels: size/M, approved, lgtm

#269 Fixed the linting issues for min and max
  pkg/apis/serving/v1/stagepodautoscaler_lifecycle_test.go
  pkg/reconciler/autoscaling/kpa/kpa.go
  pkg/reconciler/autoscaling/kpa/scaler.go
  pkg/reconciler/autoscaling/kpa/scaler_test.go
  pkg/reconciler/rolloutorchestrator/strategies/base.go
Labels: size/M, approved, lgtm

#274 [release-1.15] Update the Kind version into v1.30.x
  .github/workflows/kind-e2e.yaml
Labels: approved, size/S, lgtm

#275 Update the version for github actions
  .github/workflows/kind-e2e.yaml
Labels: approved, size/S, lgtm

#278 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/deploy.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/meta.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#279 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/caching/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/fake/fake_image.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/image.go
  vendor/knative.dev/caching/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/caching/pkg/client/listers/caching/v1alpha1/image.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#281 [release-1.16] Upgraded the hack tool to fix patch release issue
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/pkg/reconciler/labeler/accessors.go
  vendor/knative.dev/serving/pkg/reconciler/revision/reconcile_resources.go
  vendor/knative.dev/serving/pkg/reconciler/service/resources/configuration.go
  vendor/knative.dev/serving/pkg/testing/functional.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#282 [release-1.15] Updated the hack tool to fix the patch release issues
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#283 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#284 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#286 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
