Repository knative-extensions/serving-progressive-rollout, pull requests merged in 2025-02, with the labels that each got.

#287 Resume the development of 1.18
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#292 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#293 [release-1.15] Update the serving version to 1.15.3
  .github/workflows/kind-e2e.yaml
  .golangci.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/reconciler/configuration/config/store.go
  vendor/knative.dev/serving/pkg/reconciler/labeler/accessors.go
  vendor/knative.dev/serving/pkg/reconciler/revision/reconcile_resources.go
  vendor/knative.dev/serving/pkg/reconciler/service/resources/configuration.go
  vendor/knative.dev/serving/pkg/testing/functional.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#294 [release-1.16] Upgrade Serving to 1.16.2
  .github/workflows/kind-e2e.yaml
  .golangci.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/serving/pkg/reconciler/configuration/config/store.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#295 [release-1.17] Updated the github actions
  .github/workflows/kind-e2e.yaml
  .golangci.yaml
Labels: approved, size/S, lgtm

#296 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
